services:
  - type: web
    name: n8n-ffmpeg
    env: docker
    plan: free
    dockerfilePath: ./n8n-ffmpeg/Dockerfile
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: jad
      - key: N8N_BASIC_AUTH_PASSWORD
        value: n8n1234
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
